#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Endpoints.Events.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Widul")]
	public partial class EventsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertVW_Event(VW_Event instance);
    partial void UpdateVW_Event(VW_Event instance);
    partial void DeleteVW_Event(VW_Event instance);
    #endregion
		
		public EventsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["WidulConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EventsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EventsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EventsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EventsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VW_Event> VW_Events
		{
			get
			{
				return this.GetTable<VW_Event>();
			}
		}
		
		public System.Data.Linq.Table<EventDetail> EventDetails
		{
			get
			{
				return this.GetTable<EventDetail>();
			}
		}
		
		public System.Data.Linq.Table<EventComment> EventComments
		{
			get
			{
				return this.GetTable<EventComment>();
			}
		}
		
		public System.Data.Linq.Table<EventTag> EventTags
		{
			get
			{
				return this.GetTable<EventTag>();
			}
		}
		
		public System.Data.Linq.Table<Knowledge> Knowledges
		{
			get
			{
				return this.GetTable<Knowledge>();
			}
		}
		
		public System.Data.Linq.Table<Creator> Creators
		{
			get
			{
				return this.GetTable<Creator>();
			}
		}
		
		public System.Data.Linq.Table<NewEvent> NewEvents
		{
			get
			{
				return this.GetTable<NewEvent>();
			}
		}
		
		public System.Data.Linq.Table<Pagination> Pagination
		{
			get
			{
				return this.GetTable<Pagination>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_Events")]
	public partial class VW_Event : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<System.DateTime> _date;
		
		private System.DateTime _createdAt;
		
		private string _description;
		
		private string _locarion;
		
		private string _name;
		
		private System.DateTime _updateAt;
		
		private System.Guid _token;
		
		private string _type_name;
		
		private System.Guid _type_token;
		
		private string _user_fullName;
		
		private System.Guid _user_token;
		
		private string _knowledge_name;
		
		private System.Guid _knowledge_token;
		
		private string _user_photo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OncreatedAtChanging(System.DateTime value);
    partial void OncreatedAtChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnlocarionChanging(string value);
    partial void OnlocarionChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnupdateAtChanging(System.DateTime value);
    partial void OnupdateAtChanged();
    partial void OntokenChanging(System.Guid value);
    partial void OntokenChanged();
    partial void Ontype_nameChanging(string value);
    partial void Ontype_nameChanged();
    partial void Ontype_tokenChanging(System.Guid value);
    partial void Ontype_tokenChanged();
    partial void Onuser_fullNameChanging(string value);
    partial void Onuser_fullNameChanged();
    partial void Onuser_tokenChanging(System.Guid value);
    partial void Onuser_tokenChanged();
    partial void Onknowledge_nameChanging(string value);
    partial void Onknowledge_nameChanged();
    partial void Onknowledge_tokenChanging(System.Guid value);
    partial void Onknowledge_tokenChanged();
    partial void Onuser_photoChanging(string value);
    partial void Onuser_photoChanged();
    #endregion
		
		public VW_Event()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="EVN_Date", Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="EVN_CreatedAt", Storage="_createdAt", DbType="DateTime NOT NULL")]
		public System.DateTime createdAt
		{
			get
			{
				return this._createdAt;
			}
			set
			{
				if ((this._createdAt != value))
				{
					this.OncreatedAtChanging(value);
					this.SendPropertyChanging();
					this._createdAt = value;
					this.SendPropertyChanged("createdAt");
					this.OncreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="EVN_Description", Storage="_description", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="EVN_Location", Storage="_locarion", DbType="VarChar(500)")]
		public string locarion
		{
			get
			{
				return this._locarion;
			}
			set
			{
				if ((this._locarion != value))
				{
					this.OnlocarionChanging(value);
					this.SendPropertyChanging();
					this._locarion = value;
					this.SendPropertyChanged("locarion");
					this.OnlocarionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="EVN_Name", Storage="_name", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="EVN_UpdatedAt", Storage="_updateAt", DbType="DateTime NOT NULL")]
		public System.DateTime updateAt
		{
			get
			{
				return this._updateAt;
			}
			set
			{
				if ((this._updateAt != value))
				{
					this.OnupdateAtChanging(value);
					this.SendPropertyChanging();
					this._updateAt = value;
					this.SendPropertyChanged("updateAt");
					this.OnupdateAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="EVN_Token", Storage="_token", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid token
		{
			get
			{
				return this._token;
			}
			set
			{
				if ((this._token != value))
				{
					this.OntokenChanging(value);
					this.SendPropertyChanging();
					this._token = value;
					this.SendPropertyChanged("token");
					this.OntokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="EVT_Name", Storage="_type_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string type_name
		{
			get
			{
				return this._type_name;
			}
			set
			{
				if ((this._type_name != value))
				{
					this.Ontype_nameChanging(value);
					this.SendPropertyChanging();
					this._type_name = value;
					this.SendPropertyChanged("type_name");
					this.Ontype_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="EVT_Token", Storage="_type_token", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid type_token
		{
			get
			{
				return this._type_token;
			}
			set
			{
				if ((this._type_token != value))
				{
					this.Ontype_tokenChanging(value);
					this.SendPropertyChanging();
					this._type_token = value;
					this.SendPropertyChanged("type_token");
					this.Ontype_tokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="USR_FullName", Storage="_user_fullName", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string user_fullName
		{
			get
			{
				return this._user_fullName;
			}
			set
			{
				if ((this._user_fullName != value))
				{
					this.Onuser_fullNameChanging(value);
					this.SendPropertyChanging();
					this._user_fullName = value;
					this.SendPropertyChanged("user_fullName");
					this.Onuser_fullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="USR_Token", Storage="_user_token", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid user_token
		{
			get
			{
				return this._user_token;
			}
			set
			{
				if ((this._user_token != value))
				{
					this.Onuser_tokenChanging(value);
					this.SendPropertyChanging();
					this._user_token = value;
					this.SendPropertyChanged("user_token");
					this.Onuser_tokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="KNW_Name", Storage="_knowledge_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string knowledge_name
		{
			get
			{
				return this._knowledge_name;
			}
			set
			{
				if ((this._knowledge_name != value))
				{
					this.Onknowledge_nameChanging(value);
					this.SendPropertyChanging();
					this._knowledge_name = value;
					this.SendPropertyChanged("knowledge_name");
					this.Onknowledge_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="KNW_Token", Storage="_knowledge_token", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid knowledge_token
		{
			get
			{
				return this._knowledge_token;
			}
			set
			{
				if ((this._knowledge_token != value))
				{
					this.Onknowledge_tokenChanging(value);
					this.SendPropertyChanging();
					this._knowledge_token = value;
					this.SendPropertyChanged("knowledge_token");
					this.Onknowledge_tokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="USR_Photo", Storage="_user_photo", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string user_photo
		{
			get
			{
				return this._user_photo;
			}
			set
			{
				if ((this._user_photo != value))
				{
					this.Onuser_photoChanging(value);
					this.SendPropertyChanging();
					this._user_photo = value;
					this.SendPropertyChanged("user_photo");
					this.Onuser_photoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_Event")]
	public partial class EventDetail
	{
		
		private string _name;
		
		private string _description;
		
		private System.Nullable<System.DateTime> _date;
		
		private string _location;
		
		private System.DateTime _updateAt;
		
		private System.DateTime _createdAt;
		
		private System.Guid _token;
		
		private Creator _creator;
		
		private Knowledge _knowledge;
		
		private List<EventTag> _tags;
		
		private string _type_name;
		
		public EventDetail()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="EVN_Name", Storage="_name", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="EVN_Description", Storage="_description", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this._description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="EVN_Date", Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="EVN_Location", Storage="_location", DbType="VarChar(500)")]
		public string location
		{
			get
			{
				return this._location;
			}
			set
			{
				if ((this._location != value))
				{
					this._location = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="EVN_UpdatedAt", Storage="_updateAt", DbType="DateTime NOT NULL")]
		public System.DateTime updateAt
		{
			get
			{
				return this._updateAt;
			}
			set
			{
				if ((this._updateAt != value))
				{
					this._updateAt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="EVN_CreatedAt", Storage="_createdAt", DbType="DateTime NOT NULL")]
		public System.DateTime createdAt
		{
			get
			{
				return this._createdAt;
			}
			set
			{
				if ((this._createdAt != value))
				{
					this._createdAt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="EVN_Token", Storage="_token", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid token
		{
			get
			{
				return this._token;
			}
			set
			{
				if ((this._token != value))
				{
					this._token = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creator", CanBeNull=false)]
		public Creator creator
		{
			get
			{
				return this._creator;
			}
			set
			{
				if ((this._creator != value))
				{
					this._creator = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_knowledge", CanBeNull=false)]
		public Knowledge knowledge
		{
			get
			{
				return this._knowledge;
			}
			set
			{
				if ((this._knowledge != value))
				{
					this._knowledge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tags", CanBeNull=false)]
		public List<EventTag> tags
		{
			get
			{
				return this._tags;
			}
			set
			{
				if ((this._tags != value))
				{
					this._tags = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="EVT_Name", Storage="_type_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string type_name
		{
			get
			{
				return this._type_name;
			}
			set
			{
				if ((this._type_name != value))
				{
					this._type_name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_EventComment")]
	public partial class EventComment
	{
		
		private string _comment;
		
		private System.DateTime _createdAt;
		
		private System.Guid _token;
		
		public EventComment()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="COM_Comment", Storage="_comment", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string comment
		{
			get
			{
				return this._comment;
			}
			set
			{
				if ((this._comment != value))
				{
					this._comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="COM_createdAt", Storage="_createdAt", DbType="DateTime NOT NULL")]
		public System.DateTime createdAt
		{
			get
			{
				return this._createdAt;
			}
			set
			{
				if ((this._createdAt != value))
				{
					this._createdAt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="COM_Token", Storage="_token", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid token
		{
			get
			{
				return this._token;
			}
			set
			{
				if ((this._token != value))
				{
					this._token = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_EventTag")]
	public partial class EventTag
	{
		
		private string _name;
		
		private System.Guid _token;
		
		public EventTag()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TAG_Name", Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TAG_Token", Storage="_token", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid token
		{
			get
			{
				return this._token;
			}
			set
			{
				if ((this._token != value))
				{
					this._token = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_Knowledge")]
	public partial class Knowledge
	{
		
		private string _name;
		
		private System.Guid _token;
		
		public Knowledge()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="KNW_Name", Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="KNW_Token", Storage="_token", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid token
		{
			get
			{
				return this._token;
			}
			set
			{
				if ((this._token != value))
				{
					this._token = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_User")]
	public partial class Creator
	{
		
		private string _fullName;
		
		private string _email;
		
		private System.DateTime _updateAt;
		
		private System.DateTime _createdAt;
		
		private System.Guid _token;
		
		private string _photo;
		
		public Creator()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="USR_FullName", Storage="_fullName", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string fullName
		{
			get
			{
				return this._fullName;
			}
			set
			{
				if ((this._fullName != value))
				{
					this._fullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="USR_Email", Storage="_email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="USR_UpdateAt", Storage="_updateAt", DbType="DateTime NOT NULL")]
		public System.DateTime updateAt
		{
			get
			{
				return this._updateAt;
			}
			set
			{
				if ((this._updateAt != value))
				{
					this._updateAt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="USR_CreatedAt", Storage="_createdAt", DbType="DateTime NOT NULL")]
		public System.DateTime createdAt
		{
			get
			{
				return this._createdAt;
			}
			set
			{
				if ((this._createdAt != value))
				{
					this._createdAt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="USR_Token", Storage="_token", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid token
		{
			get
			{
				return this._token;
			}
			set
			{
				if ((this._token != value))
				{
					this._token = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="USR_Photo", Storage="_photo", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string photo
		{
			get
			{
				return this._photo;
			}
			set
			{
				if ((this._photo != value))
				{
					this._photo = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_Event")]
	public partial class NewEvent
	{
		
		private string _name;
		
		private string _description;
		
		private System.Nullable<System.DateTime> _date;
		
		private string _location;
		
		private System.Guid _knowledge;
		
		private System.Guid _type;
		
		private System.Guid _creator;
		
		private List<String> _tags;
		
		public NewEvent()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="EVN_Name", Storage="_name", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="EVN_Description", Storage="_description", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this._description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="EVN_Date", Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="EVN_Location", Storage="_location", DbType="VarChar(500)")]
		public string location
		{
			get
			{
				return this._location;
			}
			set
			{
				if ((this._location != value))
				{
					this._location = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="KNW_Token", Storage="_knowledge", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid knowledge
		{
			get
			{
				return this._knowledge;
			}
			set
			{
				if ((this._knowledge != value))
				{
					this._knowledge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="EVT_Token", Storage="_type", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="USR_Token", Storage="_creator", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid creator
		{
			get
			{
				return this._creator;
			}
			set
			{
				if ((this._creator != value))
				{
					this._creator = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tags", CanBeNull=false)]
		public List<String> tags
		{
			get
			{
				return this._tags;
			}
			set
			{
				if ((this._tags != value))
				{
					this._tags = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Pagination
	{
		
		private int _limit;
		
		private int _offset;
		
		private int _total;
		
		public Pagination()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Limit", Storage="_limit")]
		public int limit
		{
			get
			{
				return this._limit;
			}
			set
			{
				if ((this._limit != value))
				{
					this._limit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Offset", Storage="_offset")]
		public int offset
		{
			get
			{
				return this._offset;
			}
			set
			{
				if ((this._offset != value))
				{
					this._offset = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Total", Storage="_total")]
		public int total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this._total = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
