<?xml version="1.0" encoding="utf-8"?><Database Name="Widul" Class="EventTypesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\MSSQLSERVER_2012;Initial Catalog=Widul;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="WidulConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TB_EventType" Member="TB_EventTypes">
    <Type Name="TB_EventType">
      <Column Name="EVT_Name" Member="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EVT_Code" Member="code" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="EVT_Token" Member="token" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>