<?xml version="1.0" encoding="utf-8"?><Database Name="Widul" Class="TagsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=Widul;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="WidulConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.VW_Tags" Member="VW_Tag">
    <Type Name="VW_Tag">
      <Column Name="TAG_Name" Member="name" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>